import Button from '@/components/atoms/Button';
import Input from '@/components/molecules/Input';
import Link from '@/components/atoms/Link';
import styles from '../styles/auth.module.scss';
import Head from 'next/head';

export default function Login() {
  return (
    <>
      <Head>
        <title>Design System | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form className="auth">
          <h1 className={styles.title}>Sign in</h1>
          <div className={styles.redirection}>
            <span className={styles.body}>You don’t have an account ?</span>
            <Link href="./register">Sign Up</Link>
          </div>
          <Input label="Email" type="mail" placeholder="example@mail.com" />
          <Input label="Password" type="password" placeholder="password..." />
          <Link href="./reset-password">Forget password ?</Link>
          <Button sizeValue="lg">Sign in</Button>
        </form>
      </main>
    </>
  );
}
